version: '3.8'
services:
  qdrant:
    volumes:
      - '$PWD/qdrant/data:/qdrant/storage'
    ports:
      - '6333:6333'
    image: qdrant/qdrant

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql/init/:/docker-entrypoint-initdb.d/
      - $PWD/mysql/data:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Str0ngPassw0rd
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  bibliothecarius:
    build: bibliothecarius
    volumes:
      - '$PWD/bibliothecarius/config:/config'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - qdrant

  web:
    build: web
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://bibliothecarius:8080
    depends_on:
      - bibliothecarius
