spring:
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://xxx:3306/ai_librarian?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
  mvc:
    async:
      request-timeout: 30000

openai:
  api-key: xxx

qdrant:
  host: http://xxx



storage:
  # Cannot start with "/" and must end with "/"，The default value is ""
  dir: data/
  # The default value is 3600
  downloadExpiryTime: 3600
  endpoint: https://oss-cn-beijing.aliyuncs.com
  keyid: xx
  keysecret: xx
  bucket-name: xx


ali-parser:
  endpoint: docmind-api.cn-hangzhou.aliyuncs.com
  keyid: xxx
  keysecret: xxx